spring:
    cloud:
        config:
            discovery:
                enabled: true
            server:
                git:
                    uri: ${HOME}/git/sampleConfig

eureka:
    client:
        serviceUrl:
            defaultZone: http://discovery:8761/eureka/
server:
    port: 8888