spring:
    cloud:
        config:
            discovery:
                enabled: true
            server:
                git:
                    uri: ${HOME}/git/sampleConfig
server:
    port: 8888