server:
    port: 10001

spring:
    application:
        name: insurance-api-gateway
    cloud:
        config:
            uri: http://locahost:8888
eureka:
    client:
        serviceUrl:
            defaultZone: http://discovery:8761/eureka