spring:
    cloud:
        config:
            discovery:
                enabled: true
            server:
                git:
                    uri: http://github.com/leqcar/sampleConfig

eureka:
    client:
        serviceUrl:
            defaultZone: http://valet-discovery-service:9761/eureka/
server:
    port: 8888